#pragma once

#define CAN_BUS_BAUDRATE 1000000
#define CAN_BUS_CRX_PIN 26
#define CAN_BUS_CTX_PIN 25

#define LIBCANARD_ALLOCATION_BUFFER_IN_BYTES 2000  //minimun 1000 bytes

#define UAVCAN_MAX_BYTES_ON_MESSAGE 255 //UAVCAN_v1 up to 255 bytes

#define DEFAULT_NODE_ID 42
#define MILLISECONDS_BETWEEN_NODE_STATUS_PUBLISHES 500  //MIN: 2 - MAX: 1000
#define NODE_STATUS_VENDOR_SPECIFIC_STATUS_CODE 500

#define MAX_NUMBER_OF_PARAMETERS 25

#define NAME_FOR_INVALID_PARAMETER "INVALID"