all:
	@$(MAKE) --no-print-directory -C tests_CAN_arduino/
	@$(MAKE) --no-print-directory -C tests_CAN_ESP_IDF/

clean:
	@$(MAKE) clean --no-print-directory -C tests_CAN_arduino/
	@$(MAKE) clean --no-print-directory -C tests_CAN_ESP_IDF/