#This makefile run the different unit tests

all:
	@$(MAKE) --no-print-directory -C tests_DroneCAN_message_sender/
	@$(MAKE) --no-print-directory -C tests_DroneCAN_service_API/
clean:
	@$(MAKE) --no-print-directory -C tests_DroneCAN_message_sender/
	@$(MAKE) clean --no-print-directory -C tests_DroneCAN_service_API/