#This makefile run the different unit tests

all:
	@$(MAKE) --no-print-directory -C tests_general/
	@$(MAKE) --no-print-directory -C tests_publish_message/

clean:
	@$(MAKE) clean --no-print-directory -C tests_general/
	@$(MAKE) clean --no-print-directory -C tests_publish_message/